
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
- group: 'SDLPLC Authenticode Credentials'
steps:
- pwsh: |
    Copy-Item -Path .\Modules\ -Destination "$env:Build_ArtifactStagingDirectory" -Recurse
    Copy-Item -Path .\*.ps1 -Destination "$env:Build_ArtifactStagingDirectory"
  displayName: 'copy files to $(Build.ArtifactStagingDirectory)'

- task: TrustedSigning@0
  displayName: Sign with Trusted Signing
  inputs:
    AzureTenantID: '$(TenantID)'
    AzureClientID: '$(SigningClientId)'
    AzureClientSecret: '$(SigningSecret)'
    ExcludeVisualStudioCredential: true
    ExcludeVisualStudioCodeCredential: true
    ExcludeAzureCliCredential: true
    ExcludeAzurePowerShellCredential: true
    Endpoint: 'https://weu.codesigning.azure.net/'
    CodeSigningAccountName: 'sdl-limited'
    CertificateProfileName: 'Codesigning'
    FilesFolder: '$(Build.ArtifactStagingDirectory)'
    FilesFolderFilter: 'ps1,psm1,psd1,dll'
    FilesFolderRecurse: true
    FilesFolderDepth: '5'
    FileDigest: 'SHA256'
    TimestampRfc3161: 'http://timestamp.acs.microsoft.com'
    TimestampDigest: 'SHA256'
    description: 'sign studio-powershell-toolkit'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'studio-powershell-toolkit'
    publishLocation: 'Container'